### ISSUE TITLE
CIP-0006 social contacts

### ISSUE THREAD

**Issue by mkazlauskas** [cardano-foundation/CIPs#142]
JSON schema 'contact' has all social accounts required. This means you can't set contacts without having **every** social account listed in schema. This is not sustainable as some platforms will die in the future.

Question: schema in master branch is different from the one in [cips.cardano.org](https://cips.cardano.org/cips/cip6/). Which one is the most up-to-date?

@papacarp @gufmar

**Comment by rhyslbw** [comment]
@crptmppt can you please advise on this:

> Question: schema in master branch is different from the one in cips.cardano.org. Which one is the most up-to-date?

We'll create an amendment proposal if wishing to pursue the primary issue further @mkazlauskas

**Comment by crptmppt** [comment]
@rhyslbw the autogen site builds from the github, it seems strange that it would be out of sync. In case of conflicts, check the Github page

**Comment by KtorZ** [comment]
The problem is that the `schema.json` file does not match the schema given in the `README.md` for that CIP; and perhaps, the root cause of the problem: why does this CIP reference (what should be) the same schema twice. 

I'd advise to:

1. Fix the standalone shema.json
2. Remove completely the full schema from the README
3. Refer to the standalone schema.json in the README, in place where the schema was inlined.

**Comment by mkazlauskas** [comment]
> The problem is that the `schema.json` file does not match the schema given in the `README.md` for that CIP; and perhaps, the root cause of the problem: why does this CIP reference (what should be) the same schema twice.

Indeed the social contacts are not required in README, didn't notice that. It's also aligned with what's on cips.cardano.org
