### ISSUE TITLE
CIP-1694 | Lost ADAs and Maintaining Voting Integrity

### ISSUE THREAD

**Issue by SFzip** [cardano-foundation/CIPs#480]
Explore a strategy for incorporating inaccessible ADAs resulting from the demise of the holder. If substantial quantities are irretrievable, it could influence the potential voting percentage in comparison to the existing circulating supply.

**Comment by rphair** [comment]
This question presumes the ada owned by a non-voting stake account will somehow influence the vote distribution.  I don't see how that's possible because voting registration will be voluntary... the only question so far seems to be whether or not voting will somehow be compulsory.  In any case, voting processes won't be influenced by the "dead" staking accounts being able to vote.

Also, as I recall, any percentage of voting share needing to pass for certain special actions to be taken is a percentage of _registered_ voting share rather than the total Ada capital as you may be thinking.  Any realistic view of voter registration in fact presumes that only a fraction of Ada holders will register to vote even under ideal circumstances.

You can accept this as an answer or post your reservation here: https://github.com/cardano-foundation/CIPs/pull/380 ... if substantially different then it will inform both of us.  I'll also see your question if it's posted there and will follow any ensuing discussion.  Therefore closing this because any discussion of this issue (if not trivially answered) should continue there, not here.

**Comment by Ryun1** [comment]
I agree with @rphair. I think this query/issue should be posted in #380.
