### ISSUE TITLE
CIP-0068: resolving conflicts with validity & auth tokens

### ISSUE THREAD

**Issue by waalge** [cardano-foundation/CIPs#639]
Token twinning, where there is a validity token locked at a script address and auth token at  a user addess is a common pattern. 
This pattern is part of CIP-68. However, CIP-68 also specifies a datum standard that is too restrictive general purposes.

What do CIP guardians and other stakeholders think is best? 

We could 

- no new cip : use the labels as described in CIP-68, ignore the datum and get some broken interop with current and future tools.
- new cip : add additional prefixes, say, `010, 022, ... ` to the reg to mean "like cip68 but no assumption on datum"

**Comment by rphair** [comment]
@waalge it sounds like a good topic for a [Cardano Problem Statement (CPS)](https://github.com/cardano-foundation/CIPs/blob/master/CIP-9999/README.md) rather than a CIP: given that there may not be an immediate, universally recommended solution & currently multiple approaches to consider, as well as perhaps relevance to other token standards beyond CIP-68.

**Comment by waalge** [comment]
https://github.com/cardano-foundation/CIPs/pull/640
