### ISSUE TITLE
Add References section to CIPs/CPSs

### ISSUE THREAD

**Issue by Ryun1** [cardano-foundation/CIPs#731]
Should we add a References section to CIPs or CPSs?

Inspired by [#638 comment](https://github.com/cardano-foundation/CIPs/pull/638#discussion_r1439333464)

**Comment by rphair** [comment]
I'd be in favour of `## References`, but it should be an optional section and if so it would be our first optional section in the template.  That usually leads also to ambiguities about where it's placed, but most authors tend to put it before `## Copyright` and if they don't then we can just move it there.

I had actually been feeling bad about having to inline these Referenes which doesn't always suit the flow of what the author is saying.  I would been in favour of keeping it in the template after the last big remodel of CIP-0001 but none of the suggestions I made at the time were incorporated (though over time we've had to add all of them since then).

Unless objection from @Crypto2099 or possibly @KtorZ, and with a heads-up to @fill-the-fill @katomm who are parsing these for the Dev Portal, I can restore this in https://github.com/cardano-foundation/CIPs/pull/730.

**Comment by michaelpj** [comment]
I am probably a great sinner but I often add additional sections to my CIPs. For example, the SOPs CIP had an `Appendices` section. 

I wonder if we should just say "you can add extra sections if that is useful, e.g. References, Appendices"? It's not clear that we benefit much from asserting that there are no additional sections, or that it makes rendering any harder.

**Comment by rphair** [comment]
Parsability on derived sites like the Dev Portal CIP folder and `cips.cardano.org` was a main issue in the last major revision where this became a requirement.  @KtorZ was adamant about it & I've been trying to get him to chime in about implementing some of these rules universally in the older CIPs but he seems to have moved on.

So I think instead we have to consider the intent in why that was set up, and since really pushing #389 I had to think "Should we still do this?" about every one of these standardisations before implementing them over 40 times.  Mainly: most of these rules that were added after 2 years were added because of editing & indexing difficulties that we'd have again if those rules weren't there.

We don't see the consequences of extra sections much with a small archive, but we will when there are 10x as many CIPs: often with more than one covering the same issue & so will more frequently have to compare them in parallel.

Brevity and concise reference also become greater issues then: is a Reference useful without an inline link to the material which it refers to?  And is an Appendix, which some readers but not all will read... and which by nature is outside the flow of a CIP's essentials... not better off in a linked Markdown file: as are schemas, tables, and other material that might also be useful as externally linked technical documents in their own right?

Another original decision which I have hated implementing, but force myself to comply with because of what happened in those "bad old days" that created haphazard CIPs and massive editing overhead, was the cumbersome titles for `Motivation` and `Rationale`.  But today every time I add those "big & stupid" extra phrases, especially the unwieldy `#` anchor to those sections, I remember I am helping this & other CIP authors stay focused on separating the `Why` from the `How` of what is being proposed.

Unlike RFCs I believe CIPs are evolving as hypertext documents rather than stand-alones and so as imagined in the mid-90s I think they have to use structure like internal linking and multiple inter-linked document files in order to do the most good.  If this is done sincerely, anything said in a CIP will fall into the categories of {why, what, how} ≡ {Motivation, Specification, Rationale}.

**Comment by michaelpj** [comment]
> Parsability on derived sites like the Dev Portal CIP folder and cips.cardano.org was a main issue in the last major revision where this became a requirement.

I don't really understand. At the moment every CIP is a standalone markdown file that you can just render directly, and I don't see why you would need to parse them further.

> Unlike RFCs I believe CIPs are evolving as hypertext documents rather than stand-alones and so as imagined in the mid-90s

I feel your desire here, but I think if you want to do this you should be using something that has a proper document model and support for multiple linked documents, like RST (or https://mystmd.org/). Then you don't have the problem with references: you have proper semantic markdown for it and you can generate a bibliography in a standard way. Trying to make standard Markdown fit into that model is IMO doomed. Markdown is great for simple text documents, but it sounds like you don't want a simple text document.

**Comment by KtorZ** [comment]
It should be _fine_ (from a tooling perspective at least) to add extra sections indeed; what's often problematic is changing any of the yaml front-matter data in the preamble. 

When it comes to adding custom sections, I'd rather have that part of CIP-0001 even as an optional part, because it helps reaching better consistency between CIPs.

**Comment by rphair** [comment]
@KtorZ @michaelpj - then I think we will have both consistency + flexibility by putting the mandatory sections first, and then the optional sections after (before the final Copyright).

N.B. in #389 I haven't been removing any non-standard sections that I can recall.  There were a few cases e.g. one section appearing as an Appendix which in fact was Rationale for the CIP and so I moved it in there... and similar restructurings.

On the other hand I can imagine some cases where Appendices might be less intimately related to the CIP structure but still useful for readers at the author's discretion.  But this also has the advantage that the tertiary material fits in better at the end of the document after the primary sections.

Finally I would think all would work well if the optional sections were in a group but without having to specify any order.  For instance, in some cases References would apply to the primary (mandatory) CIP sections while in others it would also apply to the optional material: so likewise these should be ordered however the author arranges it.

See changes as of here: https://github.com/cardano-foundation/CIPs/pull/730#issuecomment-1878125650

**Comment by rphair** [comment]
Fixed by https://github.com/cardano-foundation/CIPs/pull/730.

**Comment by katomm** [comment]
The developer portal does not care about additional sections. Example: https://developers.cardano.org/docs/governance/cardano-improvement-proposals/cip-0085/#datatypes-using-data

**Comment by rphair** [comment]
Fixed even more (for CPS as well) by https://github.com/cardano-foundation/CIPs/pull/756.

**Comment by rphair** [comment]
Fully resolved with merging of #756.
