### ISSUE TITLE
Project Enlisting - Rethinking Post-Chang

### ISSUE THREAD

**Issue by Ryun1** [cardano-foundation/CIPs#898]
_How do we navigate this **Brave New World?**_

### Context

- [Project enlistment within the CIP process](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0001#project-enlisting) was introduced to solve a few problems:
  -  There's always _someone_ able to assess the feasibility of CIPs proposed by "foreigners" (i.e. people not in the core teams)
  - There were many occurrences in the past of CIPs directly affecting the ledger that were impossible to move forward because their ultimate approval and implementation was in the hands of people not engaging with the CIP process.
  -  So it was made it an opt-in procedure where projects that are willing to engage with the CIP process would (1) explicitly subscribe to the process, (2) would appoint at least one *individual* to review and approve CIPs and (3) define the additional rules by which they wish to be engaged.

- With the emergence of Cardano's Voltaire era, the ecosystem is moving away from the old guard where IOG/IOHK teams decide direction for the core technologies.
  - Thus having just IOG/IOHK-based teams enlisted does not make align

### Thoughts

- The CIP process should remain agnostic to what gets implemented and deployed to Cardano
  - It never has been nor should be the role of CIPs
  - Rather the CIP process lends itself to be a community driven process to refine technical problems and solutions
  - Currently the vision for planning what does get implemented and deployed is based on Intersect working groups and committees.

The main issue I see here is
- That for enlisted projects JUST defining reviews from IOG/IOHK as necessary cannot/ shouldnt continue

**Comment by rphair** [comment]
thanks @Ryun1 - the _Context_ is as good a history as I remember it and I agree we have to adopt a more informal engagement with the `Ledger` and `Plutus` categories that "enlistment" was primarily established for.

I think these adjustments will adapt the documented CIP process to what we will now be doing:
* dropping all the requirements for "enlistment" since there is no way we can support or require it going forward (as agreed at the last CIP meeting, but subject to further consideration including @perturbing suggestions);
* combining the enlisted & unrestricted (unenlisted) categories into a single list; since there is now no longer any way to differentiate between them;
  * e.g. there won't be much more authority in `Plutus` CIP approval than there's been for `Wallet` approval... in both cases a relatively small list of possible implementors but by no means a single organisation anymore;
* a concise categorisation "statement" stating simply that "not just _any_ `Category:` can be put in the header", but rather it must be one of the already listed categories in the table, with any new categories needing to be added to CIP-0001 first _by editor & community review_;
* adding these 2 currently-needed categories;
  * `Consensus` (https://github.com/cardano-foundation/CIPs/pull/872#discussion_r1702422743)
  * `Network` (https://github.com/cardano-foundation/CIPs/pull/876#discussion_r1710151948)
* the lesser attention to "enlistment" will transfer to a _greater_ attention paid to _Path to Active_ submissions, since delineating the process for checking an implementation and establishing an `Active` status will have to be tuned to what parts of the community can do it best: according to the PR discussion of each CIP.

The latter point would include, whenever possible, the oversight of any applicable "Intersect working groups and committees" so we will start seeing _and requiring_ these in _Path to Active_ more often (and that I need to learn more about these working groups myself).

If this can be marked OK here by some editors and/or "enlisted" contacts then I will submit the appropriate CIP-0001 modifications (half-written already).

* It would also be good to add a Wiki page on this once the details are worked out: including the resolutions that are made here: especially to keep the history & context that will no longer be in CIP-0001 itself after those edits are made.

cc @lehins @WhatisRT (`Ledger`)
cc @zliu41 (`Plutus`)
cc @stevenj (`Catalyst` ... though never formalised)
cc @Crypto2099

**Comment by perturbing** [comment]
Regarding this, please note that we also have [this](https://github.com/cardano-foundation/CIPs/blob/3299017cbb3c65fb824b62b5d327587eb1305bb9/CIP-0035/README.md?plain=1#L184) outdated.

As MPJ, is no longer in the plutus team. But the question remains, should a specific name be even listed there?

**Comment by rphair** [comment]
I guess then there should be a single PR (I can do this) which:
* corrects the above listed things (if agreed all around) in CIP-0001;
* substitutes MPJ with @zliu41 in CIP-0035;
* eliminates or corrects any language in CIP-0035 and CIP-0084 (cc @lehins @WhatisRT) that requires enlisted project teams and/or their team leads to approve submissions in that category.

**Comment by Ryun1** [comment]
> dropping all the requirements for "enlistment" since there is no way we can support or require it going forward (as agreed at the last CIP meeting, but subject to further consideration including @perturbing suggestions);

I feel there might be some middle path, rather than removing requirements entirely

What if we;
- Create enlistment proposals for the missing "core categories" of `Networking` and `Consensus`
  - Where anyone who is interested (not just IOG-based teams) in these categories is able to put themselves forward as an interested party to review proposals
  -  and anyone who is interested is able to suggest requirements for `Networking` and `Consensus` CIPs.
- Keep project enlistment as it is for the "non-core" Cardano aspects, such as `Catalyst`.

**Comment by rphair** [comment]
> Create enlistment proposals for the missing "core categories" of `Networking` and `Consensus`

Cross-referencing relevant discussions I'm aware of:

@dndales said here (https://github.com/cardano-foundation/CIPs/pull/872#discussion_r1706965548) they've been working on a CIP for the `Consensus` category already, with a goal of completing by end-of-quarter (https://github.com/IntersectMBO/ouroboros-consensus/issues/1205).

No such commitments about `Network` that I know of, but some support for the category has already been shown (beginning at https://github.com/cardano-foundation/CIPs/pull/876#discussion_r1708880748) from @ch1bo @abailly @coot @jpraynaud so maybe they could indicate whether they'd prefer to author such a CIP or add themselves to it.

**Comment by coot** [comment]
@rphair, could you post links to how Ledger & Plutus categories are dealt with?

**Comment by rphair** [comment]
@coot - pending any revisions of "enlistment" resulting from this thread:
* `Plutus` = https://github.com/cardano-foundation/CIPs/tree/master/CIP-0035
* `Ledger` = https://github.com/cardano-foundation/CIPs/tree/master/CIP-0084

**Comment by rphair** [comment]
After a reasonable waiting period after calls for comment, I'm gathering any feedback that's come from the community, especially over these 2 new categories (just created labels for these, and applied to all pending documents):
- https://github.com/cardano-foundation/CIPs/labels/Category%3A%20Consensus
- https://github.com/cardano-foundation/CIPs/labels/Category%3A%20Network

... regarding practical conceptions of "enlistment" into a long-overdue update of CIP-0001: coming today probably.  Any suggestions please put them forward so I can work them into the new PR.

**Comment by rphair** [comment]
Pending review & acceptance, I believe this is fixed by https://github.com/cardano-foundation/CIPs/pull/924.

**Comment by rphair** [comment]
Resolved with the merging of #924.
