### ISSUE TITLE
CIP-0030: API methods for Governance E.g. Checking DRep delegation.

### ISSUE THREAD

**Issue by bakon11** [cardano-foundation/CIPs#923]
With the ERA of on chain governance(CIP-1694) upon us. Many wallets are implementing governance tools For creating/delegating to dreps and casting votes.

Are there any plans on implementing API calls to check if connected wallet is associated/delegated to a DReps?

**Comment by rphair** [comment]
cc @Ryun1 - I was also wondering if such methods will fit into CIP-0030 as opposed to one or two of the wallet APIs that might supersede it (e.g. the candidate CIP-0090 or future alternative referred to here: https://github.com/cardano-foundation/CIPs/pull/462#issuecomment-2305395806)

**Comment by Ryun1** [comment]
Hey @bakon11

> Are there any plans on implementing API calls to check if connected wallet is associated/delegated to a DReps?

Good question, in short probably not (feel free to propose something)

Having wallets serve governance data was something I avoided intentionally did not do for the CIP-30 governance extension (CIP-95).
I did this because I wanted to seek maximum adoption for CIP95/governance for wallets, so I moved the burden of indexing governance data from wallets to dApps

In general I tend to feel that the DApp specific logic (be it governance in this case) should place the indexing burden upon the DApp.

**Comment by bakon11** [comment]
@Ryun1 

Agreed, I was more specifically speaking just about maybe being able to pull the DRep info, since most wallets already support dRep creation and delegation options anyways. and everything else exactly should be handled by the dApp,

**Comment by rphair** [comment]
@bakon11 does your last comment suggest that this issue can be closed? (cc @Ryun1)

**Comment by bakon11** [comment]
Yes, thank you.
